"ALT1":
    - "name": "ALT1"
      "value": "240"
      "valueType": "Integer"
      "action": "less_than_or_equal_to"
"ALT2":
    - "name": "ALT2"
      "value": "HIGH"
      "valueType": "String"
      "action": "equal_to"
    - "name": "ALT2"
      "value": "240"
      "valueType": "Integer"
      "action": "less_than_or_equal_to"
    - "name": "ALT2"
      "value": "220"
      "valueType": "Integer"
      "action": "greater_than"
"ALT3":
    - "name": "ALT3"
      "value": "23/07/2017 13:24:00.8765"
      "valueType": "DateTime"
      "action": "is_future"
      "additionalInfo": "dd/MM/yyyy HH:mm:ss.SS"
"ALT4":
    - "name": "ALT4"
      "value": "210"
      "valueType": "Integer"
      "action": "greater_than"